language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

script:
  - vendor/bin/tester tests -s -p php
  - php temp/code-checker/src/code-checker.php --short-arrays

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
  # Install Nette Tester
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry composer create-project nette/code-checker temp/code-checker ~2

cache:
  directories:
    - $HOME/.composer/cache
